In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df.fillna(method="bfill",inplace=True)

In [4]:
df.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [36]:
from sklearn.feature_selection import SelectKBest,chi2,f_regression

In [7]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.4           3.6            1.4           0.2  Iris-setosa

In [8]:
x=df.iloc[:,0:4]
y=df.Species #y=df.iloc[:,4] 

In [9]:
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.4           3.6            1.4           0.2

In [10]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [11]:
selectk=SelectKBest(chi2,k=2)          #creating objects using parameterized constructor
#chi2 since y is classification problem
selectk.fit_transform(x,y)

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.4, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [12]:
cols=selectk.get_support(indices=True) #taking index values of select k.
cols

array([2, 3], dtype=int64)

In [13]:
new_df=df.iloc[:,cols]

In [15]:
new_df.head()

PetalLengthCm  PetalWidthCm
0            1.4           0.2
1            1.4           0.2
2            1.3           0.2
3            1.5           0.2
4            1.4           0.2

In [16]:
selectk=SelectKBest(chi2,k=1)          #creating objects using parameterized constructor
#chi2 since y is classification problem
selectk.fit_transform(x,y)

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.4],
       [1.4],
       [1.5],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.3],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
      

In [22]:
cols=selectk.get_support(indices=True) #taking index values of select k.
cols

array([0, 2, 3], dtype=int64)

In [24]:
new_df=df.iloc[:,cols]
new_df.head()

SepalLengthCm  PetalLengthCm  PetalWidthCm
0            5.1            1.4           0.2
1            4.9            1.4           0.2
2            4.7            1.3           0.2
3            4.6            1.5           0.2
4            5.4            1.4           0.2

In [25]:
selectk=SelectKBest(chi2,k=3)          #creating objects using parameterized constructor
#chi2 since y is classification problem
selectk.fit_transform(x,y)

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5.4, 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.4, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.1, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [26]:
cols=selectk.get_support(indices=True) #taking index values of select k.
cols

array([0, 2, 3], dtype=int64)

In [28]:
new_df=df.iloc[:,cols]
new_df.head()

SepalLengthCm  PetalLengthCm  PetalWidthCm
0            5.1            1.4           0.2
1            4.9            1.4           0.2
2            4.7            1.3           0.2
3            4.6            1.5           0.2
4            5.4            1.4           0.2

# Regression

In [32]:
x=df.iloc[:,[0,1,3,4]]
y=df.iloc[:,2] 

In [33]:
x.head()

SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0            5.1           3.5           0.2  Iris-setosa
1            4.9           3.0           0.2  Iris-setosa
2            4.7           3.2           0.2  Iris-setosa
3            4.6           3.1           0.2  Iris-setosa
4            5.4           3.6           0.2  Iris-setosa

In [34]:
y.head()

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: PetalLengthCm, dtype: float64

## label encoding to treat the categorical variable into numerical

In [38]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x["Species"]=le.fit_transform(x["Species"])

<ipython-input-38-44d8bd290c56>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Species"]=le.fit_transform(x["Species"])


In [39]:
selectk=SelectKBest(f_regression,k=2)          #creating objects using parameterized constructor
#f_regression since y is regression problem
selectk.fit_transform(x,y)

array([[0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.4, 0. ],
       [0.3, 0. ],
       [0.3, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.2, 0. ],
       [0.5, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.3, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.6, 0. ],
       [0.4, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [1.4, 1. ],
       [1.5, 1. ],
       [1.5,