In [1]:
import pandas as pd
import numpy as np


In [2]:
df= pd.read_csv("Iris-f.csv")

In [4]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            NaN           3.6            1.4           0.2  Iris-setosa

In [5]:
df.isna().sum()

SepalLengthCm    2
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          2
dtype: int64

In [6]:
df["species"]=df["Species"].fillna(method="bfill")

In [7]:
df.isna().sum()

SepalLengthCm    2
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          2
species          0
dtype: int64

In [8]:
df1=df.copy(deep=True)

In [9]:
df["species"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [13]:
m={"Iris-virginica":3,"Iris-setosa":2,"Iris-versicolor":1}

In [20]:
df1.Species.value_counts()

Iris-virginica     50
Iris-versicolor    49
Iris-setosa        49
Name: Species, dtype: int64

In [14]:
df1["species"]=df1["species"].map(m)

In [15]:
df1["species"]

0      2
1      2
2      2
3      2
4      2
      ..
145    3
146    3
147    3
148    3
149    3
Name: species, Length: 150, dtype: int64

In [18]:
df1.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0            5.1           3.5            1.4           0.2  Iris-setosa   
1            4.9           3.0            1.4           0.2  Iris-setosa   
2            4.7           3.2            1.3           0.2  Iris-setosa   
3            4.6           3.1            1.5           0.2  Iris-setosa   
4            NaN           3.6            1.4           0.2  Iris-setosa   

   species  
0        2  
1        2  
2        2  
3        2  
4        2

In [21]:
df2=df.copy(deep=True)

In [22]:
from sklearn.preprocessing import LabelEncoder

In [28]:
ob= LabelEncoder()
ob.fit_transform(df2["species"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
df2["Species"]=ob.fit_transform(df2["species"])

In [33]:
df3=df.copy(deep=True)

In [43]:
from sklearn.preprocessing import OneHotEncoder
ob=OneHotEncoder()
# x=df3[["species"]]
converted=ob.fit_transform(df3[["species"]]).toarray()

In [49]:
new_df=pd.DataFrame(converted,columns=["setosa","versicolor","virginica"])
new_df

setosa  versicolor  virginica
0       1.0         0.0        0.0
1       1.0         0.0        0.0
2       1.0         0.0        0.0
3       1.0         0.0        0.0
4       1.0         0.0        0.0
..      ...         ...        ...
145     0.0         0.0        1.0
146     0.0         0.0        1.0
147     0.0         0.0        1.0
148     0.0         0.0        1.0
149     0.0         0.0        1.0

[150 rows x 3 columns]

In [47]:
df3=pd.merge(left=df3,right=new_df,left_index=True,right_index=True)

In [48]:
df3.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0            5.1           3.5            1.4           0.2  Iris-setosa   
1            4.9           3.0            1.4           0.2  Iris-setosa   
2            4.7           3.2            1.3           0.2  Iris-setosa   
3            4.6           3.1            1.5           0.2  Iris-setosa   
4            NaN           3.6            1.4           0.2  Iris-setosa   

       species  setosa_x  versicolor_x  virginica_x  setosa_y  versicolor_y  \
0  Iris-setosa       1.0           0.0          0.0       1.0           0.0   
1  Iris-setosa       1.0           0.0          0.0       1.0           0.0   
2  Iris-setosa       1.0           0.0          0.0       1.0           0.0   
3  Iris-setosa       1.0           0.0          0.0       1.0           0.0   
4  Iris-setosa       1.0           0.0          0.0       1.0           0.0   

   virginica_y  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

In [50]:
df4=df.copy(deep=True)

In [52]:
pd.get_dummies(df4["species"])

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [53]:
converted1=pd.get_dummies(df4["species"])

In [54]:
type(converted1)

pandas.core.frame.DataFrame

##### MinMax scaling - uses normalization
##### standard scaling - user standardization
##### Binarizer - either 0 or 1 based on threshold 



In [59]:
from sklearn.preprocessing import MinMaxScaler

mm=MinMaxScaler(feature_range=(1,4))

x=df4.iloc[:,0:4]

mm.fit_transform(x)

array([[1.66666667, 2.875     , 1.20338983, 1.125     ],
       [1.5       , 2.25      , 1.20338983, 1.125     ],
       [1.33333333, 2.5       , 1.15254237, 1.125     ],
       [1.25      , 2.375     , 1.25423729, 1.125     ],
       [       nan, 3.        , 1.20338983, 1.125     ],
       [1.91666667, 3.375     , 1.3559322 , 1.375     ],
       [1.25      , 2.75      , 1.20338983, 1.25      ],
       [1.58333333,        nan,        nan, 1.125     ],
       [1.08333333, 2.125     , 1.20338983, 1.125     ],
       [1.5       , 2.375     , 1.25423729, 1.        ],
       [1.91666667, 3.125     , 1.25423729, 1.125     ],
       [1.41666667, 2.75      , 1.30508475, 1.125     ],
       [1.41666667, 2.25      , 1.20338983, 1.        ],
       [1.        , 2.25      , 1.05084746, 1.        ],
       [2.25      , 3.5       , 1.10169492, 1.125     ],
       [2.16666667, 4.        , 1.25423729, 1.375     ],
       [1.91666667, 3.375     , 1.15254237, 1.375     ],
       [1.66666667, 2.875     ,

In [ ]:
# mm=MinMaxScaler(feature_range=(0,1))

# x_scaled= mmscaler.fit_transform(x)

In [63]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()

x=df4.iloc[:,0:4]

ss.fit_transform(x)

array([[-9.09218146e-01,  1.03619829e+00, -1.35289577e+00,
        -1.31297673e+00],
       [-1.15102279e+00, -1.19442019e-01, -1.35289577e+00,
        -1.31297673e+00],
       [-1.39282744e+00,  3.42814106e-01, -1.40988799e+00,
        -1.31297673e+00],
       [-1.51372976e+00,  1.11686044e-01, -1.29590355e+00,
        -1.31297673e+00],
       [            nan,  1.26732636e+00, -1.35289577e+00,
        -1.31297673e+00],
       [-5.46511177e-01,  1.96071054e+00, -1.18191912e+00,
        -1.05003079e+00],
       [-1.51372976e+00,  8.05070232e-01, -1.35289577e+00,
        -1.18150376e+00],
       [-1.03012047e+00,             nan,             nan,
        -1.31297673e+00],
       [-1.75553441e+00, -3.50570082e-01, -1.35289577e+00,
        -1.31297673e+00],
       [-1.15102279e+00,  1.11686044e-01, -1.29590355e+00,
        -1.44444970e+00],
       [-5.46511177e-01,  1.49845442e+00, -1.29590355e+00,
        -1.31297673e+00],
       [-1.27192512e+00,  8.05070232e-01, -1.23891134e+00,
      

In [64]:
from sklearn.preprocessing import Binarizer

Br=Binarizer(threshold=2)

x=df4.iloc[:,0:4]

x=x.dropna()

Br.fit_transform(x)

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
