In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("Iris-f.csv")

In [3]:
df.fillna(method="bfill",inplace=True)

In [4]:
df.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [5]:
from sklearn.feature_selection import SelectKBest,chi2,f_regression

In [6]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.4           3.6            1.4           0.2  Iris-setosa

In [7]:
x=df.iloc[:,0:4]
y=df.Species #y=df.iloc[:,4] 

In [8]:
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.4           3.6            1.4           0.2

In [9]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [10]:
selectk=SelectKBest(chi2,k=2)          #creating objects using parameterized constructor
#chi2 since y is classification problem
selectk.fit_transform(x,y)

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.4, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [11]:
cols=selectk.get_support(indices=True) #taking index values of select k.
cols

array([2, 3], dtype=int64)

In [12]:
new_df=df.iloc[:,cols]

In [13]:
new_df.head()

PetalLengthCm  PetalWidthCm
0            1.4           0.2
1            1.4           0.2
2            1.3           0.2
3            1.5           0.2
4            1.4           0.2

In [14]:
selectk=SelectKBest(chi2,k=1)          #creating objects using parameterized constructor
#chi2 since y is classification problem
selectk.fit_transform(x,y)

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.4],
       [1.4],
       [1.5],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.3],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
      

In [15]:
cols=selectk.get_support(indices=True) #taking index values of select k.
cols

array([2], dtype=int64)

In [16]:
new_df=df.iloc[:,cols]
new_df.head()

PetalLengthCm
0            1.4
1            1.4
2            1.3
3            1.5
4            1.4

In [17]:
selectk=SelectKBest(chi2,k=3)          #creating objects using parameterized constructor
#chi2 since y is classification problem
selectk.fit_transform(x,y)

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5.4, 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.4, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.1, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [18]:
cols=selectk.get_support(indices=True) #taking index values of select k.
cols

array([0, 2, 3], dtype=int64)

In [19]:
new_df=df.iloc[:,cols]
new_df.head()

SepalLengthCm  PetalLengthCm  PetalWidthCm
0            5.1            1.4           0.2
1            4.9            1.4           0.2
2            4.7            1.3           0.2
3            4.6            1.5           0.2
4            5.4            1.4           0.2

# Regression

In [20]:
x=df.iloc[:,[0,1,3,4]]
y=df.iloc[:,2] 

In [21]:
x.head()

SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0            5.1           3.5           0.2  Iris-setosa
1            4.9           3.0           0.2  Iris-setosa
2            4.7           3.2           0.2  Iris-setosa
3            4.6           3.1           0.2  Iris-setosa
4            5.4           3.6           0.2  Iris-setosa

In [22]:
y.head()

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: PetalLengthCm, dtype: float64

## label encoding to treat the categorical variable into numerical

In [26]:
from sklearn.feature_selection import f_regression
selectk=SelectKBest(f_regression,k=2)          
#creating objects using parameterized constructor
#f_regression since y is regression problem
selectk.fit_transform(x,y)

array([[5.1, 0.2],
       [4.9, 0.2],
       [4.7, 0.2],
       [4.6, 0.2],
       [5.4, 0.2],
       [5.4, 0.4],
       [4.6, 0.3],
       [5. , 0.2],
       [4.4, 0.2],
       [4.9, 0.1],
       [5.4, 0.2],
       [4.8, 0.2],
       [4.8, 0.1],
       [4.3, 0.1],
       [5.8, 0.2],
       [5.7, 0.4],
       [5.4, 0.4],
       [5.1, 0.3],
       [5.7, 0.3],
       [5.1, 0.3],
       [5.1, 0.2],
       [5.1, 0.4],
       [4.6, 0.2],
       [5.1, 0.5],
       [4.8, 0.2],
       [5. , 0.2],
       [5. , 0.4],
       [5.2, 0.2],
       [5.2, 0.2],
       [4.7, 0.2],
       [4.8, 0.2],
       [5.4, 0.4],
       [5.2, 0.1],
       [5.5, 0.2],
       [4.9, 0.1],
       [5. , 0.2],
       [5.5, 0.2],
       [4.9, 0.1],
       [4.4, 0.2],
       [5.1, 0.2],
       [5. , 0.3],
       [4.5, 0.3],
       [4.4, 0.2],
       [5. , 0.6],
       [5.1, 0.4],
       [4.8, 0.3],
       [5.1, 0.2],
       [4.6, 0.2],
       [5.3, 0.2],
       [5. , 0.2],
       [7. , 1.4],
       [6.4, 1.5],
       [6.9,

In [24]:
x= df.iloc[:,0:4]

In [28]:
from sklearn.decomposition import PCA

pca=PCA(n_components=2)
x_new=pca.fit_transform(x)

In [29]:
type(x_new)

numpy.ndarray

In [30]:
new_df=pd.DataFrame(x_new,columns=["comp1","comp2"])

In [31]:
new_df

comp1     comp2
0   -2.683775  0.331738
1   -2.715973 -0.164505
2   -2.889894 -0.131903
3   -2.746601 -0.305910
4   -2.583455  0.601475
..        ...       ...
145  1.944153  0.187409
146  1.524793 -0.374945
147  1.764275  0.078478
148  1.902997  0.116210
149  1.390154 -0.282440

[150 rows x 2 columns]

In [32]:
new_df.head()

comp1     comp2
0 -2.683775  0.331738
1 -2.715973 -0.164505
2 -2.889894 -0.131903
3 -2.746601 -0.305910
4 -2.583455  0.601475

In [33]:
from sklearn.model_selection import train_test_split

xt,xtest,yt,ytest=train_test_split(x,y,test_size=0.25,random_state=1,shuffle=True)

In [34]:
xtest.shape

(38, 4)

In [35]:
xt.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
54             6.5           2.8            4.6           1.5
108            6.7           2.5            5.8           1.8
112            6.8           3.0            5.5           2.1
17             5.1           3.5            1.4           0.3
119            6.0           2.2            5.0           1.5

In [38]:
yt.value_counts()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
4.9            3.1           1.5            0.1             3
5.8            2.7           5.1            1.9             2
5.1            3.4           1.7            0.2             1
               3.5           1.4            0.2             1
                                            0.3             1
                                                           ..
6.3            3.3           6.0            2.5             1
               3.4           5.6            2.4             1
6.4            2.7           5.3            1.9             1
               2.8           5.6            2.2             1
4.3            3.0           1.1            0.1             1
Length: 109, dtype: int64